services:
  _defaults:
    autowire: true
    autoconfigure: true

  Crtl\RequestDTOResolverBundle\RequestDTOResolver:

  Crtl\RequestDTOResolverBundle\EventSubscriber\RequestDtoValidationEventSubscriber:


